[2022-09-17 14:43:55,023] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.t2 scheduled__2022-09-16T00:00:00+00:00 [queued]>
[2022-09-17 14:43:55,139] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.t2 scheduled__2022-09-16T00:00:00+00:00 [queued]>
[2022-09-17 14:43:55,139] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 14:43:55,140] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-17 14:43:55,140] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 14:43:55,401] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): t2> on 2022-09-16 00:00:00+00:00
[2022-09-17 14:43:55,414] {standard_task_runner.py:52} INFO - Started process 1664 to run task
[2022-09-17 14:43:55,429] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 't2', 'scheduled__2022-09-16T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpgsp5lv_a', '--error-file', '/tmp/tmpypx3ok9o']
[2022-09-17 14:43:55,429] {standard_task_runner.py:80} INFO - Job 20: Subtask t2
[2022-09-17 14:43:55,772] {task_command.py:369} INFO - Running <TaskInstance: xcom_dag.t2 scheduled__2022-09-16T00:00:00+00:00 [running]> on host 3f1973d04161
[2022-09-17 14:43:56,538] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2022-09-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-16T00:00:00+00:00
[2022-09-17 14:43:56,718] {logging_mixin.py:115} INFO - 42
[2022-09-17 14:43:56,719] {python.py:173} INFO - Done. Returned value was: None
[2022-09-17 14:43:56,798] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=t2, execution_date=20220916T000000, start_date=20220917T144355, end_date=20220917T144356
[2022-09-17 14:43:56,972] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-17 14:43:57,204] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
